### ISSUE TITLE
Add Http PATCH

### ISSUE THREAD

**Issue by bloodstar** [vipm-io/HTTP-REST-Client#27]
I am using REST API to connect to Siemens Polarion which [suggest using HTTP PATCH](https://docs.sw.siemens.com/en-US/doc/230235217/PL20220419389880191.xid2134849/xid2138466) to update data.
NIs base LabviewHTTPClient.lvlib does not support PATCH, but [ni_lib_advanced_http_client_api](https://www.vipm.io/package/ni_lib_advanced_http_client_api/ ) does. Any chance to include it?

**Comment by francois-normandin** [comment]
@bloodstar I attached a proposed build in PR #28 , in case you'd like to give it a spin.
I do not have any website to test the PATCH method, but I assumed it was nothing different than the other methods.
Comments appreciated.

**Comment by bloodstar** [comment]
That was quick! Guess the topic was already in the pipeline. Will check it out today.

**Comment by ChrisCilinoGC** [comment]
@bloodstar did this work for you? I tried installing and the rest vis are all broken. I see many vis linking against the adv http client that points to the following dll:
C:\Program Files (x86)\National Instruments\LabVIEW 2020\vi.lib\NI\Advanced HTTP Client\lvwebclient_32.dll
even though I had installed version 2.1.0.33 to 64 bit labview. Oh wow... and for whatever reasons the rest api vis are located at: C:\Program Files\National Instruments\LabVIEW 2020\vi.lib\addons\_JKI.lib\_REST Client_internal_deps\
 
So stuff is majorly broken. 

Can you confirm?

**Comment by francois-normandin** [comment]
Linking to this folder: `addons_JKI.lib\REST Client_internal_deps` is the result of using internal dependencies (easier to install offline) which might not be suitable for this package since it uses different DLLs for 32 and 64-bit. However, your cross-linking problems might also be from the build being done with 32-bit LV2020.

Considering that the NI Advanced HTTP package is now on LV Community Repository, it is a safe course of action to change the pull request for a package source build that does not include the code as an internal Dependency but rather relies on the original NI package.
I`ll amend my merge request accordingly.

**Comment by francois-normandin** [comment]
@ChrisCilinoGC I updated to External dependencies, rebuilt and tested on a LV0222Q3 64-bit deployment.
Check out PR #28 again. Let me know if that does not work for you!

**Comment by jimkring** [comment]
Merged PR #28, so I'll close this one.
